"""Baseline schema: documents, chunks, embeddings, jobs, queries, eval_runs.

Written by hand rather than autogenerated, so that the pgvector extension, the
generated tsvector column and both index types are explicit and reviewable.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = 384


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("filename", sa.String(512), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False, unique=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("page_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("char_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", sa.String(32), nullable=False, server_default="queued"),
        sa.Column("full_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("pages", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("meta", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_documents_sha256", "documents", ["sha256"])

    op.create_table(
        "chunks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("index_name", sa.String(64), nullable=False, server_default="default"),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("page_char_start", sa.Integer(), nullable=False),
        sa.Column("page_char_end", sa.Integer(), nullable=False),
        sa.Column("page_spans", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("clause_id", sa.String(64), nullable=True),
        sa.Column("clause_title", sa.String(256), nullable=True),
        sa.Column("token_estimate", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "chunk_strategy", sa.String(32), nullable=False, server_default="clause-aware"
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=True,
        ),
        sa.UniqueConstraint(
            "document_id", "index_name", "ordinal", name="uq_chunk_position"
        ),
    )
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"])
    op.create_index("ix_chunks_index_name", "chunks", ["index_name"])
    op.create_index(
        "ix_chunks_search_vector", "chunks", ["search_vector"], postgresql_using="gin"
    )

    op.create_table(
        "embeddings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "chunk_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("chunks.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(64), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vector", Vector(EMBEDDING_DIM), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("chunk_id", "provider", name="uq_embedding_chunk_provider"),
    )
    op.create_index("ix_embeddings_chunk_id", "embeddings", ["chunk_id"])
    # HNSW rather than IVFFlat: no training step, no list count to tune, and the corpus
    # is small enough that build time does not matter. See ADR-0002.
    op.execute(
        "CREATE INDEX ix_embeddings_vector_hnsw ON embeddings "
        "USING hnsw (vector vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )

    op.create_table(
        "jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("kind", sa.String(32), nullable=False, server_default="ingest"),
        sa.Column("state", sa.String(32), nullable=False, server_default="queued"),
        sa.Column("progress", sa.Float(), nullable=False, server_default="0"),
        sa.Column("detail", sa.String(256), nullable=False, server_default=""),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("timings_ms", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_jobs_document_id", "jobs", ["document_id"])

    op.create_table(
        "queries",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("request_id", sa.String(64), nullable=False),
        sa.Column(
            "document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("config_hash", sa.String(16), nullable=False),
        sa.Column("retrieval_ms", sa.Float(), nullable=False, server_default="0"),
        sa.Column("rerank_ms", sa.Float(), nullable=False, server_default="0"),
        sa.Column("generation_ms", sa.Float(), nullable=False, server_default="0"),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("completion_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_usd", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_queries_request_id", "queries", ["request_id"])
    op.create_index("ix_queries_config_hash", "queries", ["config_hash"])

    op.create_table(
        "eval_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", sa.String(128), nullable=False, unique=True),
        sa.Column("git_sha", sa.String(40), nullable=False, server_default=""),
        sa.Column("dataset", sa.String(128), nullable=False, server_default=""),
        sa.Column("config", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("metrics", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("status", sa.String(16), nullable=False, server_default="ok"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_eval_runs_run_id", "eval_runs", ["run_id"])


def downgrade() -> None:
    op.drop_table("eval_runs")
    op.drop_table("queries")
    op.drop_table("jobs")
    op.execute("DROP INDEX IF EXISTS ix_embeddings_vector_hnsw")
    op.drop_table("embeddings")
    op.drop_table("chunks")
    op.drop_table("documents")
